"""
Quantum-specific Configuration for r5.2 Pipeline (but I needed to break it down to get a clearer picture in my mind)
"""
from src.config import (
    SEEDS, DATA_SIZES, N_OUTER_FOLDS, N_INNER_FOLDS,
    BASE_DIR, PAD_DIM,
    N_QUBITS, N_LAYERS, NN_HIDDEN, NN_DEPTH, PRE_HIDDEN,
    OPTUNA_INNER_TRIALS_QUANTUM,
    RESULTS_QUANTUM_DIR, CHECKPOINT_QUANTUM_DIR,
)

INPUT_DIM = PAD_DIM 

LEARNING_RATE = 0.010438
EPOCHS        = 40
BATCH_SIZE    = 5

OPTUNA_INNER_TRIALS = OPTUNA_INNER_TRIALS_QUANTUM

QUANTUM_CHECKPOINT_DIR = CHECKPOINT_QUANTUM_DIR
QUANTUM_RESULTS_DIR    = RESULTS_QUANTUM_DIR
